### PR TITLE
Remove duplicate logic

### LINKED ISSUE #180: LABELS_TO_MEASURE causes the action to fail
If LABELS_TO_MEASURE is set then the action will fail with:

```
Starting issue-metrics search...
  File "/action/workspace/issue_metrics.py", line 331, in <module>
    main()
  File "/action/workspace/issue_metrics.py", line 262, in main
    labels = labels.split(",")
             ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'split'
```
It looks like the block [here](https://github.com/github/issue-metrics/blob/main/issue_metrics.py#L261) is redundant after [this PR](https://github.com/github/issue-metrics/pull/171) which already converts the environment string to a list.

### PR DESCRIPTION
**Pull request by parkerbxyz**
## Proposed Changes

I found some logic in `issue_metrics.py` that is duplicating environment variable processing already happening via `get_env_vars()` in `config.py`, which was introduced in #171.

https://github.com/github/issue-metrics/blob/ebc6a99b31b69b73a26678b9ac5a6ebbc021c663/config.py#L61-L71

Duplicate logic:

https://github.com/github/issue-metrics/blob/ebc6a99b31b69b73a26678b9ac5a6ebbc021c663/issue_metrics.py#L260-L264

https://github.com/github/issue-metrics/blob/ebc6a99b31b69b73a26678b9ac5a6ebbc021c663/issue_metrics.py#L140-L141

Removing this duplicate logic fixes #180.

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request
- [x] run `make lint` and fix any issues that you have introduced
- [x] run `make test` and ensure you have test coverage for the lines you are introducing

### Reviewer
- [x] Label as either `bug`, `documentation`, `enhancement`, `infrastructure`, or `breaking`

### CODE REVIEW

**Review by zkoppert — APPROVED** [review]
Thanks for the contribution! good find!
